apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webserver

spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-webserver
        someotherlabel: blub
        depl: py-webserv
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 759 # just pick a random user ID as longs as its numeric.
      serviceAccountName: python-webserver-service-account
      containers:
        - image: docker.io/library/python-webserver:latest
          name: python-webserver
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 1